### ISSUE TITLE
Everytime onhit, the avatar or NPC will be zapped

### ISSUE THREAD

**Issue by waveyl** [Sliperr34/PM_World#13]
Is it intended?

**Comment by Sliperr34** [comment]
Please specify exactly where you found it (in the game or in the code). Or send a screenshot if possible

**Comment by Sliperr34** [comment]
Oh, I see what you mean. Now I will be looking for a solution to the problem

**Comment by Sliperr34** [comment]
Solved! Thanks for feedback!
