### ISSUE TITLE
Book for Zwei quest not spawning in libraries

### ISSUE THREAD

**Issue by Dacelty** [Sliperr34/PM_World#23]
Twice now I've been designated libraries that are full of books, but not a single Zombie Survival Guide.
I think the spawn has been moved to somewhere else a while ago, or the book is not spawning on shelves in the first place (?), or there is a mistake on your end.
Version: cdda-windows-tiles-sounds-x64-2024-09-22-0113.

**Comment by Sliperr34** [comment]
Hi! I have investigated this issue, and here's what I can say:
![image](https://github.com/user-attachments/assets/5fa04cc9-639c-494c-afbd-333c53c5d6e5)
Book is spawning as intended
However, I know that in some rare cases, mission cannot find a suitable bookstore and therefore does not spawn the book

Please note that you need a bookstore and not a library, it will also be marked with a mission pointer, so make sure that you have an active mission selected

And even if you can't find this book, there are other places where you can find it. With the highest chance it can be apartment complex and regional school
